#This code is auto generated code, don't Edit it 
outpvar.cur.addfcdata("main2");
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs({})));
outpvar.cur.fcalldata["main2"].cur.addfcdata("header4");
outpvar.cur.fcalldata["main2"].addchilds(newtag_header4({}, ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["header4"].root.content).root.content);
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs({"class": "container"})));
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs({"class": "row"})));
outpvar.cur.fcalldata["main2"].cur.addfcdata("textdiv");
outpvar.cur.fcalldata["main2"].addchilds(newtag_textdiv({"name": "My Cart", "class": "bigtext"}, ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["textdiv"].root.content).root.content);
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs({"class": "row"})));
outpvar.cur.fcalldata["main2"].open(htmlnode("table", extentattrs({"class": "bordered"})));
outpvar.cur.fcalldata["main2"].open(htmlnode("thead", extentattrs({})));
for i in forlist(["delivery Date", "Chef", "", "Dish", "Price", "No. of plates", "Delivery Slot", "Status"]) :
  outpvar.cur.fcalldata["main2"].open(htmlnode("th", extentattrs({})));
  outpvar.cur.fcalldata["main2"].open(htmlnode("p", extentattrs(i)));
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("tbody", extentattrs({})));
for ii in range(len(forlist(ginp["cartl"]))) :
  i = ginp["cartl"][ii];
  outpvar.cur.fcalldata["main2"].open(htmlnode("tr", extentattrs({"class": "cartitems", "datas": {"datetime": i["datetime"], "cid": i["cid"], "lord": i["lord"], "dishid": i["dishid"]}})));
  outpvar.cur.fcalldata["main2"].open(htmlnode("td", extentattrs({})));
  outpvar.cur.fcalldata["main2"].open(htmlnode("p", extentattrs(i["datetimetext"])));
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].open(htmlnode("td", extentattrs({})));
  outpvar.cur.fcalldata["main2"].cur.addfcdata("profilea1");
  outpvar.cur.fcalldata["main2"].addchilds(newtag_profilea1({"name": i["name"], "uid": i["cid"]}, ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["profilea1"].root.content).root.content);
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].open(htmlnode("td", extentattrs({})));
  outpvar.cur.fcalldata["main2"].open(htmlnode("p", extentattrs({"l": "Lunch", "d": "Dinner"}[i["lord"]])));
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].open(htmlnode("td", extentattrs({})));
  outpvar.cur.fcalldata["main2"].open(htmlnode("p", extentattrs(i["title"])));
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].open(htmlnode("td", extentattrs({})));
  outpvar.cur.fcalldata["main2"].cur.addfcdata("icon1");
  outpvar.cur.fcalldata["main2"].addchilds(newtag_icon1({"img": "photo/inr2.png"}, ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["icon1"].root.content).root.content);
  outpvar.cur.fcalldata["main2"].open(htmlnode("span", extentattrs({"class": "itemprice"})));
  outpvar.cur.fcalldata["main2"].open(htmlnode("p", extentattrs(i["price"])));
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].open(htmlnode("td", extentattrs({})));
  outpvar.cur.fcalldata["main2"].cur.addfcdata("select1");
  outpvar.cur.fcalldata["main2"].addchilds(newtag_select1({"tlist": i["tlist"], "aclass": "numitem", "attr": {"onchange": "settotalprice();"}}, ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["select1"].root.content).root.content);
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].open(htmlnode("td", extentattrs({})));
  outpvar.cur.fcalldata["main2"].cur.addfcdata("select1");
  outpvar.cur.fcalldata["main2"].addchilds(newtag_select1({"tlist": ginp["dslots"][i["lord"]], "aclass": "dslots"}, ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["select1"].root.content).root.content);
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].open(htmlnode("td", extentattrs({})));
  outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs({"style": {"color": "red"}, "data": {"iserror": int((i["error"] != ""))}})));
  outpvar.cur.fcalldata["main2"].open(htmlnode("p", extentattrs(i["error"])));
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].open(htmlnode("td", extentattrs({})));
  outpvar.cur.fcalldata["main2"].cur.addfcdata("button1");
  outpvar.cur.fcalldata["main2"].addchilds(newtag_button1({"name": "Delete", "data": {"onclick": "sreq", "action": "delfromcart", "restext": "Deleted", "res": "removerow(obj);"}, "datas": {"id": i["id"]}}, ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["button1"].root.content).root.content);
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs({"class": "row"})));
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs({"class": "col l12"})));
outpvar.cur.fcalldata["main2"].open(htmlnode("span", extentattrs({"style": {"font-size": "25px"}})));
outpvar.cur.fcalldata["main2"].open(htmlnode("p", extentattrs("Total Price: ")));
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("span", extentattrs({"id": "totalprice"})));
outpvar.cur.fcalldata["main2"].open(htmlnode("p", extentattrs(100)));
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].cur.addfcdata("icon1");
outpvar.cur.fcalldata["main2"].addchilds(newtag_icon1({"img": "photo/inr1.png"}, ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["icon1"].root.content).root.content);
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs({"class": "col l12"})));
outpvar.cur.fcalldata["main2"].open(htmlnode("span", extentattrs({"style": {"font-size": "18px"}})));
outpvar.cur.fcalldata["main2"].open(htmlnode("p", extentattrs("Address: ")));
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("span", extentattrs({})));
outpvar.cur.fcalldata["main2"].open(htmlnode("p", extentattrs(ginp["address"][2])));
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].cur.addfcdata("a1");
outpvar.cur.fcalldata["main2"].addchilds(newtag_a1({"name": "change", "href": "", "style": {"font-size": "11px"}}, ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["a1"].root.content).root.content);
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("form", extentattrs({"data": {"action": "order", "onsubmit": "order", "bobj": "", "restext": "Ordered"}})));
outpvar.cur.fcalldata["main2"].cur.addfcdata("input1");
outpvar.cur.fcalldata["main2"].addchilds(newtag_input1({"label": "Extra Address", "id": "eaddress"}, ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["input1"].root.content).root.content);
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs({"class": "col l12"})));
outpvar.cur.fcalldata["main2"].cur.addfcdata("button1");
outpvar.cur.fcalldata["main2"].addchilds(newtag_button1({"name": "Order", "attr": {"type": "submit"}}, ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["button1"].root.content).root.content);
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs({"class": "dnone"})));
outpvar.cur.fcalldata["main2"].cur.addfcdata("textdiv");
outpvar.cur.fcalldata["main2"].addchilds(newtag_textdiv({"id": "lat", "name": ginp["address"][0]}, ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["textdiv"].root.content).root.content);
outpvar.cur.fcalldata["main2"].cur.addfcdata("textdiv");
outpvar.cur.fcalldata["main2"].addchilds(newtag_textdiv({"id": "lng", "name": ginp["address"][1]}, ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["textdiv"].root.content).root.content);
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.addchilds(newtag_main2({"js": ["js/cart.js"], "htmlstyle": {"overflow-y": "scroll"}}, ginp, outpvar.cur.fcalldata["main2"].root.content).root.content);