#This code is auto generated code, don't Edit it 
outpvar.cur.addfcdata("main2");
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].cur.addfcdata("header4");
outpvar.cur.fcalldata["main2"].addchilds(newtag_header4(cod([]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["header4"].root.content).root.content);
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "container")]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "row")]))));
outpvar.cur.fcalldata["main2"].cur.addfcdata("textdiv");
outpvar.cur.fcalldata["main2"].addchilds(newtag_textdiv(cod([("name", "My Cart"), ("class", "bigtext")]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["textdiv"].root.content).root.content);
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "row")]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("table", extentattrs(cod([("class", "bordered")]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("thead", extentattrs(cod([]))));
for i in forlist(["delivery Date", "Chef", "", "Dish", "Price", "No. of plates", "Delivery Slot", "Status"], False ) :
  outpvar.cur.fcalldata["main2"].open(htmlnode("th", extentattrs(cod([]))));
  outpvar.cur.fcalldata["main2"].open(htmlnode("p", extentattrs(i)));
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("tbody", extentattrs(cod([]))));
for ii in forlist(ginp["cartl"], True ) :
  i = ginp["cartl"][ii];
  outpvar.cur.fcalldata["main2"].open(htmlnode("tr", extentattrs(cod([("class", "cartitems"), ("datas", cod([("datetime", i["datetime"]), ("cid", i["cid"]), ("lord", i["lord"]), ("dishid", i["dishid"])]))]))));
  outpvar.cur.fcalldata["main2"].open(htmlnode("td", extentattrs(cod([]))));
  outpvar.cur.fcalldata["main2"].open(htmlnode("p", extentattrs(i["datetimetext"])));
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].open(htmlnode("td", extentattrs(cod([]))));
  outpvar.cur.fcalldata["main2"].cur.addfcdata("profilea1");
  outpvar.cur.fcalldata["main2"].addchilds(newtag_profilea1(cod([("name", i["name"]), ("uid", i["cid"])]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["profilea1"].root.content).root.content);
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].open(htmlnode("td", extentattrs(cod([]))));
  outpvar.cur.fcalldata["main2"].open(htmlnode("p", extentattrs(cod([("l", "Lunch"), ("d", "Dinner")])[i["lord"]])));
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].open(htmlnode("td", extentattrs(cod([]))));
  outpvar.cur.fcalldata["main2"].open(htmlnode("p", extentattrs(i["title"])));
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].open(htmlnode("td", extentattrs(cod([]))));
  outpvar.cur.fcalldata["main2"].cur.addfcdata("icon1");
  outpvar.cur.fcalldata["main2"].addchilds(newtag_icon1(cod([("img", "photo/inr2.png")]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["icon1"].root.content).root.content);
  outpvar.cur.fcalldata["main2"].open(htmlnode("span", extentattrs(cod([("class", "itemprice")]))));
  outpvar.cur.fcalldata["main2"].open(htmlnode("p", extentattrs(i["price"])));
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].open(htmlnode("td", extentattrs(cod([]))));
  outpvar.cur.fcalldata["main2"].cur.addfcdata("select1");
  outpvar.cur.fcalldata["main2"].addchilds(newtag_select1(cod([("tlist", i["tlist"]), ("aclass", "numitem"), ("attr", cod([("onchange", "settotalprice();")]))]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["select1"].root.content).root.content);
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].open(htmlnode("td", extentattrs(cod([]))));
  outpvar.cur.fcalldata["main2"].cur.addfcdata("select1");
  outpvar.cur.fcalldata["main2"].addchilds(newtag_select1(cod([("tlist", ginp["dslots"][i["lord"]]), ("aclass", "dslots")]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["select1"].root.content).root.content);
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].open(htmlnode("td", extentattrs(cod([]))));
  outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("style", cod([("color", "red")])), ("data", cod([("iserror", int((i["error"] != "")))]))]))));
  outpvar.cur.fcalldata["main2"].open(htmlnode("p", extentattrs(i["error"])));
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].open(htmlnode("td", extentattrs(cod([]))));
  outpvar.cur.fcalldata["main2"].cur.addfcdata("button1");
  outpvar.cur.fcalldata["main2"].addchilds(newtag_button1(cod([("name", "Delete"), ("data", cod([("onclick", "sreq"), ("action", "delfromcart"), ("restext", "Deleted"), ("res", "removerow(obj);")])), ("datas", cod([("id", i["id"])]))]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["button1"].root.content).root.content);
  outpvar.cur.fcalldata["main2"].close();
  outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "row")]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "col l12")]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("span", extentattrs(cod([("style", cod([("font-size", "25px")]))]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("p", extentattrs("Total Price: ")));
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("span", extentattrs(cod([("id", "totalprice")]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("p", extentattrs(100)));
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].cur.addfcdata("icon1");
outpvar.cur.fcalldata["main2"].addchilds(newtag_icon1(cod([("img", "photo/inr1.png")]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["icon1"].root.content).root.content);
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "col l12")]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("span", extentattrs(cod([("style", cod([("font-size", "18px")]))]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("p", extentattrs("Address: ")));
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("span", extentattrs(cod([]))));
outpvar.cur.fcalldata["main2"].open(htmlnode("p", extentattrs(ginp["address"][2])));
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].cur.addfcdata("a1");
outpvar.cur.fcalldata["main2"].addchilds(newtag_a1(cod([("name", "change"), ("href", ""), ("style", cod([("font-size", "11px")]))]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["a1"].root.content).root.content);
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("form", extentattrs(cod([("data", cod([("action", "order"), ("onsubmit", "order"), ("bobj", ""), ("restext", "Ordered")]))]))));
outpvar.cur.fcalldata["main2"].cur.addfcdata("input1");
outpvar.cur.fcalldata["main2"].addchilds(newtag_input1(cod([("label", "Extra Address"), ("id", "eaddress")]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["input1"].root.content).root.content);
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "col l12")]))));
outpvar.cur.fcalldata["main2"].cur.addfcdata("button1");
outpvar.cur.fcalldata["main2"].addchilds(newtag_button1(cod([("name", "Order"), ("attr", cod([("type", "submit")]))]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["button1"].root.content).root.content);
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs(cod([("class", "dnone")]))));
outpvar.cur.fcalldata["main2"].cur.addfcdata("textdiv");
outpvar.cur.fcalldata["main2"].addchilds(newtag_textdiv(cod([("id", "lat"), ("name", ginp["address"][0])]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["textdiv"].root.content).root.content);
outpvar.cur.fcalldata["main2"].cur.addfcdata("textdiv");
outpvar.cur.fcalldata["main2"].addchilds(newtag_textdiv(cod([("id", "lng"), ("name", ginp["address"][1])]), ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["textdiv"].root.content).root.content);
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.addchilds(newtag_main2(cod([("js", ["js/cart.js"]), ("htmlstyle", cod([("overflow-y", "scroll")]))]), ginp, outpvar.cur.fcalldata["main2"].root.content).root.content);