#This code is auto generated code, don't Edit it 
outpvar.cur.addfcdata("main2");
outpvar.cur.fcalldata["main2"].cur.addfcdata("header4");
outpvar.cur.fcalldata["main2"].addchilds(newtag_header4({}, ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["header4"].root.content).root.content);
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs({"attr": {"id": "googlemap"}})));
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs({"style": {"margin-top": "64px"}, "class": ""})));
outpvar.cur.fcalldata["main2"].open(htmlnode("img", extentattrs({"style": {"width": "100%", "position": "absolute"}, "attr": {"src": "photo/slide1.jpg"}})));
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs({"style": {"position": "relative", "top": "0px"}, "class": "valign"})));
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs({"attr": {"align": "center"}})));
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs({"class": "pagecenter container"})));
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs({"class": "row"})));
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs({"class": "col l8 offset-l2 m8 s8 offset-m2 offset-s2"})));
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs({"class": "card-panel grey lighten-5 z-depth-1"})));
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs({})));
outpvar.cur.fcalldata["main2"].open(htmlnode("b", extentattrs({"color": "black", "style": {"font-size": "25px"}})));
outpvar.cur.fcalldata["main2"].addtext("Real Food");
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs({})));
outpvar.cur.fcalldata["main2"].open(htmlnode("b", extentattrs({"color": "black", "style": {"font-size": "25px"}})));
outpvar.cur.fcalldata["main2"].addtext("Home Delivered");
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs({"style": {"width": "20%", "border-bottom": "solid black 5px", "min-height": "2px", "margin-top": "10px", "margin-bottom": "10px"}})));
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs({})));
outpvar.cur.fcalldata["main2"].open(htmlnode("b", extentattrs({"color": "black", "style": {"font-size": "16px"}})));
outpvar.cur.fcalldata["main2"].addtext("Fresh Ingredients, Daily Menus");
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs({})));
outpvar.cur.fcalldata["main2"].open(htmlnode("b", extentattrs({"color": "black", "style": {"font-size": "16px"}})));
outpvar.cur.fcalldata["main2"].addtext("No Commitment, No Fuss");
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].cur.addfcdata("height");
outpvar.cur.fcalldata["main2"].addchilds(newtag_height({"val": 20}, ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["height"].root.content).root.content);
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs({})));
outpvar.cur.fcalldata["main2"].open(htmlnode("b", extentattrs({"color": "black", "style": {"font-size": "25px"}})));
outpvar.cur.fcalldata["main2"].addtext("Launching Soon!");
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].cur.addfcdata("height");
outpvar.cur.fcalldata["main2"].addchilds(newtag_height({"val": 20}, ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["height"].root.content).root.content);
outpvar.cur.fcalldata["main2"].open(htmlnode("form", extentattrs({"attr": {"action": myadd(ginp["BASE"], "menu")}})));
outpvar.cur.fcalldata["main2"].cur.addfcdata("bigsearch");
outpvar.cur.fcalldata["main2"].addchilds(newtag_bigsearch({"ph": "Enter Your Location", "id": "locsearch", "autofocus": ""}, ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["bigsearch"].root.content).root.content);
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs({"class": "darken-4"})));
outpvar.cur.fcalldata["main2"].cur.addfcdata("height");
outpvar.cur.fcalldata["main2"].addchilds(newtag_height({"val": 200}, ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["height"].root.content).root.content);
outpvar.cur.fcalldata["main2"].cur.addfcdata("kurry_footer");
outpvar.cur.fcalldata["main2"].addchilds(newtag_kurry_footer({}, ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["kurry_footer"].root.content).root.content);
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs({"class": "modal", "id": "contactusform", "style": {"padding": "20px"}})));
outpvar.cur.fcalldata["main2"].cur.addfcdata("kurry_contactus_form");
outpvar.cur.fcalldata["main2"].addchilds(newtag_kurry_contactus_form({}, ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["kurry_contactus_form"].root.content).root.content);
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs({"class": "modal", "id": "aboutus", "style": {"padding": "20px"}})));
outpvar.cur.fcalldata["main2"].cur.addfcdata("kurry_aboutus");
outpvar.cur.fcalldata["main2"].addchilds(newtag_kurry_aboutus({}, ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["kurry_aboutus"].root.content).root.content);
outpvar.cur.fcalldata["main2"].close();
outpvar.cur.fcalldata["main2"].open(htmlnode("div", extentattrs({"class": "modal", "id": "policy", "style": {"padding": "20px"}})));
outpvar.cur.fcalldata["main2"].cur.addfcdata("kurry_policy");
outpvar.cur.fcalldata["main2"].addchilds(newtag_kurry_policy({}, ginp, outpvar.cur.fcalldata["main2"].cur.fcalldata["kurry_policy"].root.content).root.content);
outpvar.cur.fcalldata["main2"].close();
outpvar.addchilds(newtag_main2({"js": ["js/index.js", "https://maps.googleapis.com/maps/api/js?signed_in=true&libraries=drawing,places&callback=initMap"], "bodystyle": {"overflow-y": "scroll"}}, ginp, outpvar.cur.fcalldata["main2"].root.content).root.content);